name: Test flake

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DEPLOY_KEY }}
          known_hosts: unnecessary
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: cachix/cachix-action@v12
        with:
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          name: altf4llc-os
      - uses: actions/checkout@v3
      - run: cachix use "altf4llc-os"
      - run: nix develop -c just check

  build:
    needs:
      - check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        profile:
          - geist-mono
    steps:
      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DEPLOY_KEY }}
          known_hosts: unnecessary
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: cachix/cachix-action@v12
        with:
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          name: altf4llc-os
      - uses: actions/checkout@v4
      - run: cachix use "altf4llc-os"
      - run: |
          nix develop -c just build "${{ matrix.profile }}"

  build-darwin:
    needs:
      - check
    runs-on: macos-latest
    steps:
      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DEPLOY_KEY }}
          known_hosts: unnecessary
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: cachix/cachix-action@v12
        with:
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          name: altf4llc-os
      - uses: actions/checkout@v4
      - run: cachix use "altf4llc-os"
      - run: |
          nix develop -c just build \
            "darwinConfigurations.x86_64.config.system.build.toplevel"

  build-nixos:
    needs:
      - check
    runs-on: ubuntu-latest
    steps:
      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DEPLOY_KEY }}
          known_hosts: unnecessary
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: cachix/cachix-action@v12
        with:
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          name: altf4llc-os
      - uses: actions/checkout@v4
      - run: cachix use "altf4llc-os"
      - run: |
          nix develop -c just build \
            "nixosConfigurations.x86_64.config.system.build.toplevel"
