name: Test flake

on:
  pull_request:
  push:
    branches:
      - main

env:
  CACHIX_BINARY_CACHE: altf4llc-os

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: cachix/install-nix-action@v26
        with:
          enable_kvm: true
      - uses: cachix/cachix-action@v14
        with:
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          name: ${{ env.CACHIX_BINARY_CACHE }}
      - uses: actions/checkout@v3
      - run: nix develop -c just check

  build:
    needs:
      - check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        profile:
          - geist-mono
    steps:
      - uses: cachix/install-nix-action@v26
        with:
          enable_kvm: true
      - uses: cachix/cachix-action@v14
        with:
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          name: ${{ env.CACHIX_BINARY_CACHE }}
      - uses: actions/checkout@v4
      - run: nix develop -c just build "${{ matrix.profile }}"

  build-darwin:
    needs:
      - check
    runs-on: macos-latest
    steps:
      - uses: cachix/install-nix-action@v26
        with:
          enable_kvm: true
      - uses: cachix/cachix-action@v14
        with:
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          name: ${{ env.CACHIX_BINARY_CACHE }}
      - uses: actions/checkout@v4
      - run: |
          nix develop -c just build \
            "darwinConfigurations.x86_64.config.system.build.toplevel"

  build-nixos:
    needs:
      - check
    runs-on: ubuntu-latest
    steps:
      - uses: cachix/install-nix-action@v26
        with:
          enable_kvm: true
      - uses: cachix/cachix-action@v14
        with:
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          name: ${{ env.CACHIX_BINARY_CACHE }}
      - uses: actions/checkout@v4
      - run: |
          nix develop -c just build \
            "nixosConfigurations.x86_64.config.system.build.toplevel"
