name: "Test flake"

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - uses: actions/checkout@v3
    - run: nix flake check

  build-attic:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: extractions/setup-just@v1
      - uses: actions/checkout@v3
      - run: just build-attic "x86_64"

  build-darwin:
    needs: check
    runs-on: macos-latest
    steps:
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: extractions/setup-just@v1
      - uses: actions/checkout@v3
      - run: just build-darwin "x86_64"

  build-nixos:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: extractions/setup-just@v1
      - uses: actions/checkout@v3
      - run: just build-nixos "x86_64"
